kbuild: add -fno-PIE [STREAMEIGHT-3041](thud)
commit 8ae94224c9d72fc4d9aaac93b2d7833cf46d7141 upstream

Debian started to build the gcc with -fPIE by default so the kernel
build ends before it starts properly with:
|kernel/bounds.c:1:0: error: code model kernel does not support PIC mode

Also add to KBUILD_AFLAGS due to:

|gcc -Wp,-MD,arch/x86/entry/vdso/vdso32/.note.o.d … -mfentry -DCC_USING_FENTRY … vdso/vdso32/note.S
|arch/x86/entry/vdso/vdso32/note.S:1:0: sorry, unimplemented: -mfentry isn’t supported for 32-bit in combination with -fpic

Tagging it stable so it is possible to compile recent stable kernels as
well.

Cc: stable@vger.kernel.org
Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
Signed-off-by: Michal Marek <mmarek@suse.com>
[backported to kernel 4.1]
Signed-off-by: Andriy Danylovskyy <andriy.danylovskyy@streamunlimited.com>
[move lines to be above/below same lines as in upstream]
Signed-off-by: Radek Dostál <radek.dostal@streamunlimited.com>